program = { declaration } EOF ;

declaration = funcDecl | varDecl | statement ;

funcDecl = "func", IDENTIFIER, "(", [ FUNCTION_ARGS ], ")", ":", BLOCK, "end" ;
varDecl = ("var" | "final") , IDENTIFIER, [ "=", expression ] ";" ;

statement = assignmentStatement | expressionStatement | printlnStatement | returnStatement | tryCatchStatement ;

expressionStatement = expression, [ "=", expression ], ";" ;
printlnStatement = "println", "(", expression, ")" ;
returnStatement = "return", [ expression ], ";" ;
tryCatchStatement = "try", "{", BLOCK, "}", "catch", [ IDENTIFIER ], "{", BLOCK, "}" ;
ifStatement = "if", expression, "{", BLOCK, [ { "else", "if", expression, "{", BLOCK, "}" } ], [ "else", "{", BLOCK, "}" ] ;

expression = logic_or ;
logic_or = logic_and, [ { "or", logic_and } ] ;
logic_and = bitwise_or, [ { "and", bitwise_or } ] ;
bitwise_or = bitwise_xor, [ { "|", bitwise_xor } ] ;
bitwise_xor = bitwise_and, [ { "^", bitwise_and } ] ;
bitwise_and = equality, [ { "&", equality } ] ;
equality = comparison, [ { ( "!=" | "==" ), comparison } ] ;
comparison = shift, [ { ( ">" | ">=" | "<" | "<=" ), shift } ] ;
shift = term, [ { ( "<<" | ">>" ), term } ] ;
term = factor, [ { ( "-" | "+" ), factor } ] ;
factor = unary, [ { ( "/" | "*" ), unary } ] ;
unary = [ ( "!" | "-" | "~" ) ], ( unary | call ) ;
call = primary [ { "(", [ CALL_ARGS ], ")" } ] ;
primary = BOOL | NUMBER | STRING | "(", expression, ")" | TYPE | TYPEOF | LAMBDA ;

BOOL = "false" | "true" ;
FLOAT = { DIGIT }, ".", { DIGIT } ;
INT = { DIGIT } ;
NONE = "None" ;
STRING = '"', [ { all characters } ], '"' ;
TYPE = "Bool", "Float", "Int", "None", "String", "Function" ;
TYPEOF = "typeof", "(", expression, ")" ;
LAMBDA = "|", [ CAPTURE_LIST ], "|", "(", [ FUNCTION_ARGS ], ")", ":", [ { declaration } ], "end" ;

DIGIT = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ;

CAPTURE_LIST = IDENTIFIER, [ { ",", IDENTIFIER } ] ;
CALL_ARGS = expression, [ { ",", expression } ] ;
FUNCTION_ARGS = IDENTIFIER, [ { ",", IDENTIFIER } ] ;
BLOCK = [ { declaration - funcDecl } ] ;